package com.cxm.entity;

public class SysChunk {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chunk.id
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chunk.chunk_number
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    private Integer chunkNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chunk.chunk_size
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    private Long chunkSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chunk.current_chunk
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    private Long currentChunk;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chunk.filename
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chunk.identifier
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chunk.relative_path
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    private String relativePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chunk.total_chunks
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    private Integer totalChunks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_chunk.total_size
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    private Long totalSize;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chunk.id
     *
     * @return the value of sys_chunk.id
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chunk.id
     *
     * @param id the value for sys_chunk.id
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chunk.chunk_number
     *
     * @return the value of sys_chunk.chunk_number
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public Integer getChunkNumber() {
        return chunkNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chunk.chunk_number
     *
     * @param chunkNumber the value for sys_chunk.chunk_number
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public void setChunkNumber(Integer chunkNumber) {
        this.chunkNumber = chunkNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chunk.chunk_size
     *
     * @return the value of sys_chunk.chunk_size
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public Long getChunkSize() {
        return chunkSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chunk.chunk_size
     *
     * @param chunkSize the value for sys_chunk.chunk_size
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public void setChunkSize(Long chunkSize) {
        this.chunkSize = chunkSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chunk.current_chunk
     *
     * @return the value of sys_chunk.current_chunk
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public Long getCurrentChunk() {
        return currentChunk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chunk.current_chunk
     *
     * @param currentChunk the value for sys_chunk.current_chunk
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public void setCurrentChunk(Long currentChunk) {
        this.currentChunk = currentChunk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chunk.filename
     *
     * @return the value of sys_chunk.filename
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chunk.filename
     *
     * @param filename the value for sys_chunk.filename
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chunk.identifier
     *
     * @return the value of sys_chunk.identifier
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chunk.identifier
     *
     * @param identifier the value for sys_chunk.identifier
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chunk.relative_path
     *
     * @return the value of sys_chunk.relative_path
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public String getRelativePath() {
        return relativePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chunk.relative_path
     *
     * @param relativePath the value for sys_chunk.relative_path
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public void setRelativePath(String relativePath) {
        this.relativePath = relativePath == null ? null : relativePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chunk.total_chunks
     *
     * @return the value of sys_chunk.total_chunks
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public Integer getTotalChunks() {
        return totalChunks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chunk.total_chunks
     *
     * @param totalChunks the value for sys_chunk.total_chunks
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public void setTotalChunks(Integer totalChunks) {
        this.totalChunks = totalChunks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_chunk.total_size
     *
     * @return the value of sys_chunk.total_size
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public Long getTotalSize() {
        return totalSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_chunk.total_size
     *
     * @param totalSize the value for sys_chunk.total_size
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    public void setTotalSize(Long totalSize) {
        this.totalSize = totalSize;
    }
}