package com.cxm.dao;

import com.cxm.entity.SysChunk;

public interface SysChunkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chunk
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chunk
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    int insert(SysChunk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chunk
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    int insertSelective(SysChunk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chunk
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    SysChunk selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chunk
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    int updateByPrimaryKeySelective(SysChunk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_chunk
     *
     * @mbg.generated Wed Nov 27 10:24:01 CST 2024
     */
    int updateByPrimaryKey(SysChunk record);
}